### ISSUE TITLE
a question about LatentDiffusionConditional

### ISSUE THREAD

**Issue by LiuCMU** [mikonvergence/DiffusionFastForward#3]
Hey, thanks for the great tutorials!

Just a question in [this file](https://github.com/mikonvergence/DiffusionFastForward/blob/master/05-Conditional-Latent-Diffusion.ipynb): where is `LatentDiffusionConditional` from? It is called in the cell, but I don't see it is imported or implemented in the notebook. Thanks!

**Comment by mikonvergence** [comment]
Hello! Thank you.

All models are implemented in `src/`, and since this one is a type of a latent diffusion model, it is contained in [src/LatentDiffusion.py](https://github.com/mikonvergence/DiffusionFastForward/blob/master/src/LatentDiffusion.py) (line 114)

I think it would be good to make this more obvious, so I might update the notebooks soon to clarify this. Thank you for pointing it out!

**Comment by LiuCMU** [comment]
got it, thanks!
