### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by shriar** [mikonvergence/DiffusionFastForward#4]
Thanks for the tutorial. 

I am getting this error in this [02-Pixel-Diffusion.ipynb](https://github.com/mikonvergence/DiffusionFastForward/blob/master/02-Pixel-Diffusion.ipynb)  when i am running this `trainer.fit(model)`
```
TypeError: 'NoneType' object is not iterable
During handling of the above exception, another exception occurred:
.
.
.
TypeError: An invalid dataloader was returned from `PixelDiffusion.val_dataloader()`. Found None.
```

**Comment by mikonvergence** [comment]
This is likely caused by an inconsistency in a newer version of `pytorch-lightning`.

The README suggests the following installation:
```bash
pip install pytorch-lightning==1.9.3 diffusers einops
```

I just tested this on the [colab notebook](https://colab.research.google.com/github/mikonvergence/DiffusionFastForward/blob/master/02-Pixel-Diffusion-colab.ipynb) and this error does not occur.
